#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias st="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias kdiff="git difftool -y -t Kaleidoscope"
alias kmerge="git mergetool -y -t Kaleidoscope"
export VISUAL=vim
export EDITOR="$VISUAL"

